version: "3.7"
services:

#Laravel App
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: user-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./localpath/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - mynetwork
    
 #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    mem_limit: 10000m
    networks:
      - mynetwork
    logging:
      options:
          max-size: 10000m
          max-file: '100'
  #Mysl Service
  db:
    platform: linux/x86_64
    image: mysql:8
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge